### ISSUE TITLE
"There was some data missing in your request" error in Elgg 2.3.5

### ISSUE THREAD

**Issue by javery86** [ColdTrick/contact#2]
I keep receiving this message any time I try to send a message in Elgg 2.3.5.

**Comment by jdalsem** [comment]
are you using latest version of this plugin from github or from the elgg community?

the error comes when data is missing... could you analyze your POST action... do you see 'name', 'email', 'message' being sent?

**Comment by javery86** [comment]
From GitHub

**Comment by javery86** [comment]
Also, how would I analyze POST action?

**Comment by jdalsem** [comment]
This plugin is no longer maintained.
