### ISSUE TITLE
Hacked!

### ISSUE THREAD

**Issue by KavorkaDesigns** [ColdTrick/contact#3]
My contact form is automatically sending spam to my site's email address, and possible all users. Is there any way to prevent these bots without wall garden?

**Comment by jdalsem** [comment]
why do you think this is originating from this contact plugin? you could add captcha protection to the form if you have people abusing the form

**Comment by merilturock** [comment]
I have a captcha in my website but still some of the spammers make it an habit in just sending email on a daily basis. Is there any possible way that it can be checked against the stopforum for email id & akimsat for the message to be seen for spammer ??

**Comment by jdalsem** [comment]
that could be, but i think that is more a generic solution than something that is specific to this plugin, maybe suggest something like to on the elgg forums

**Comment by merilturock** [comment]
How to Disable Visual Editor of Contact Form.. Even this can help a bit in reducing the spam.. Just want a plain message box without the CK editor.. 

**Feature request:**
1) If any link is placed in the message of the contact form the contact form should simply reject the message stating "Message delivery failed bcz the message might contain spam" This can discourage the contact form being miss used.

Thank you
Meril
